# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bntGenerateKeys = QtWidgets.QPushButton(self.centralwidget)
        self.bntGenerateKeys.setGeometry(QtCore.QRect(520, 50, 81, 23))
        self.bntGenerateKeys.setObjectName("bntGenerateKeys")
        self.btnEncrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnEncrypt.setGeometry(QtCore.QRect(50, 340, 75, 23))
        self.btnEncrypt.setObjectName("btnEncrypt")
        self.btnDecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnDecrypt.setGeometry(QtCore.QRect(250, 340, 75, 23))
        self.btnDecrypt.setObjectName("btnDecrypt")
        self.btnSign = QtWidgets.QPushButton(self.centralwidget)
        self.btnSign.setGeometry(QtCore.QRect(400, 340, 75, 23))
        self.btnSign.setObjectName("btnSign")
        self.btnVerify = QtWidgets.QPushButton(self.centralwidget)
        self.btnVerify.setGeometry(QtCore.QRect(550, 340, 75, 23))
        self.btnVerify.setObjectName("btnVerify")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 10, 61, 21))
        self.label.setObjectName("label")
        self.txtTrinhHuynhQuocLam = QtWidgets.QLabel(self.centralwidget)
        self.txtTrinhHuynhQuocLam.setGeometry(QtCore.QRect(10, 80, 61, 16))
        self.txtTrinhHuynhQuocLam.setObjectName("txtTrinhHuynhQuocLam")
        self.txtEncrypt = QtWidgets.QLabel(self.centralwidget)
        self.txtEncrypt.setGeometry(QtCore.QRect(20, 190, 61, 16))
        self.txtEncrypt.setObjectName("txtEncrypt")
        self.txtHutech = QtWidgets.QLabel(self.centralwidget)
        self.txtHutech.setGeometry(QtCore.QRect(390, 80, 61, 20))
        self.txtHutech.setObjectName("txtHutech")
        self.txtSign = QtWidgets.QLabel(self.centralwidget)
        self.txtSign.setGeometry(QtCore.QRect(410, 190, 47, 13))
        self.txtSign.setObjectName("txtSign")
        self.txtplain = QtWidgets.QTextEdit(self.centralwidget)
        self.txtplain.setGeometry(QtCore.QRect(80, 80, 241, 71))
        self.txtplain.setObjectName("txtplain")
        self.txtcipher = QtWidgets.QTextEdit(self.centralwidget)
        self.txtcipher.setGeometry(QtCore.QRect(90, 190, 231, 71))
        self.txtcipher.setObjectName("txtcipher")
        self.txtinfo = QtWidgets.QTextEdit(self.centralwidget)
        self.txtinfo.setGeometry(QtCore.QRect(470, 80, 211, 71))
        self.txtinfo.setObjectName("txtinfo")
        self.txtsign = QtWidgets.QTextEdit(self.centralwidget)
        self.txtsign.setGeometry(QtCore.QRect(470, 190, 211, 71))
        self.txtsign.setObjectName("txtsign")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bntGenerateKeys.setText(_translate("MainWindow", "Generate Keys"))
        self.btnEncrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btnDecrypt.setText(_translate("MainWindow", "Decrypt"))
        self.btnSign.setText(_translate("MainWindow", "Sign"))
        self.btnVerify.setText(_translate("MainWindow", "Verify"))
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.txtTrinhHuynhQuocLam.setText(_translate("MainWindow", "Plain Text"))
        self.txtEncrypt.setText(_translate("MainWindow", "Cypher Text"))
        self.txtHutech.setText(_translate("MainWindow", "Information"))
        self.txtSign.setText(_translate("MainWindow", "Signature"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
